### ISSUE TITLE
Nützliche Links

### ISSUE THREAD

**Issue by floydsteam** [maxbachmann/esp32-aktor-modul#1]
- [MQTT mit Arduino IDE](https://slashposts.com/2018/04/mqtt-pubsubclient-tutorial-for-arduino-esp8266-esp32/) 
- [ESP32 in Arduino IDE einrichten (Youtube)](https://youtu.be/DgaKlh081tU) 
- [Esp32 mit Arduino IDE (Website)](https://randomnerdtutorials.com/installing-the-esp32-board-in-arduino-ide-windows-instructions/)
- [ESP-IDF](https://docs.espressif.com/projects/esp-idf/en/latest/index.html)

**Comment by floydsteam** [comment]
[MQTT mit SSL/TLS](http://www.iotsharing.com/2017/08/how-to-use-esp32-mqtts-with-mqtts-mosquitto-broker-tls-ssl.html?m=1)
Damit sollte es scheinbar seit letztem Jahr möglich sein, mit Verschlüsselung zu arbeiten.

**Comment by maxbachmann** [comment]
https://blog.classycode.com/secure-over-the-air-updates-for-esp32-ec25ae00db43

**Comment by maxbachmann** [comment]
https://blog.mi.hdm-stuttgart.de/index.php/2017/09/14/embedded-security-using-an-esp32/
